CREATE DATABASE FilmesDB;
GO

USE FilmesDB;
GO

CREATE TABLE Genero(
	IdGenero VARCHAR(40) PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Filme(
	IdFilme VARCHAR(40) PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL,
	Imagem VARCHAR(100) NOT NULL,
	IdGenero VARCHAR(40) FOREIGN KEY REFERENCES Genero(IdGenero)
);
GO

CREATE TABLE Usuario(
	IdUsuario VARCHAR(40) PRIMARY KEY,
	Senha VARCHAR(60) NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(256) NOT NULL,
);
GO

SELECT * FROM Genero;