CREATE DATABASE "BDConnect+";
GO

USE "BDConnect+";

CREATE TABLE TipoContato(
	idTipoContato  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(50) NOT NULL
);

GO

SELECT * FROM TipoContato


CREATE TABLE Contato(
	idContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(100) NOT NULL,
	FormaContato NVARCHAR(100) NOT NULL,
	Imagem VARCHAR(100) NOT NULL,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);

GO

SELECT * FROM Contato