CREATE DATABASE BDConnectPlus;
GO

USE BDConnectPlus;

CREATE TABLE TipoContato(
	idTipoContato  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(50) NOT NULL
);

GO

SELECT * FROM TipoContato


CREATE TABLE Contato(
	idContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo NVARCHAR(100) NOT NULL,
	FormaContato NVARCHAR(100) NOT NULL,
	Imagem VARCHAR(100) NOT NULL,
	IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);


GO

SELECT * FROM Contato